# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ basic-react-app ]
  pull_request:
    branches: [ basic-react-app ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: false
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          timenow=$(date)
          echo "version: $timenow" > testfile.txt
      
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          path: pubfolder
          ref: main
          
      - name: Copy test file
        run: cp testfile.txt pubfolder/

      - name: cat test file 
        working-directory: ./pubfolder
        run: |
          echo "******* testfile *******"
          cat testfile.txt
          
          echo "******* readme md *******"
          cat README.md
          

      - name: checkout directory list
        working-directory: ./pubfolder
        run: find .
        
      - name: Commit files
        working-directory: ./pubfolder
        run: |
          git config --local user.email "prem-github-actions[bot]@users.noreply.github.com"
          git config --local user.name "prem-github-actions[bot]"
          git add .
          git commit -m "Add testfile"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          directory: ./pubfolder
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
